apiVersion: v1
kind: Secret
metadata:
  name: secrets-environment-{{ include "optmove-frontend.fullname" . }}
data:
  VITE_APP_ENVIRONMENT: { { .Values.env.VITE_APP_ENVIRONMENT | b64enc } }
  VITE_APP_API_PTB: { { .Values.env.VITE_APP_API_PTB | b64enc } }
  VITE_APP_CLIENT_ID: { { .Values.env.VITE_APP_CLIENT_ID | b64enc } }
  VITE_APP_TENANT_ID: { { .Values.env.VITE_APP_TENANT_ID | b64enc } }
  VITE_APP_AUTHORITY: { { .Values.env.VITE_APP_AUTHORITY | b64enc } }
  VITE_APP_REDIRECT_URI: { { .Values.env.VITE_APP_REDIRECT_URI | b64enc } }
  VITE_APP_POST_LOGOUT_REDIRECT_URI: { { .Values.env.VITE_APP_POST_LOGOUT_REDIRECT_URI | b64enc } }
