trigger:
  - develop
  - main
  - homolog
  - hotfix/*
  - fetuare/*
  - devops/*
  
resources:
  - repo: self

variables:
  - name: 'JAVA_HOME_17_X64'
    value: '/usr/lib/jvm/java-17-openjdk-amd64/'
  - name: DOCKER_BUILDKIT
    value: '1'
  - group: general-pipeline
  - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/homolog') }}:
    - group: optmove-front-build-hom
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    - group: optmove-front-build-prd
  - ${{ else }}:
    - group: optmove-front-build-dev

pool:
  name: $(selfHosted)

stages:
  - stage: TESTS
    displayName: 'CI Tests'
    jobs:
      - job: Tests
        displayName: 'Unit Test and SAST'
        steps:
          - template: azure-pipelines-templates/tests.yml

  - stage: FRONT_BUILD
    displayName: 'Building FRONT'
    jobs:
      - job: BuildingFront
        displayName: 'Build and Package FRONT'
        condition: |
          or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
             eq(variables['Build.SourceBranch'], 'refs/heads/homolog'),
             eq(variables['Build.SourceBranch'], 'refs/heads/main'))
        steps:
          - template: azure-pipelines-templates/front-build.yml

  # - stage: CLEANING
  #   displayName: 'Stage cleaning'
  #   jobs:
  #     - job: DeleteFiles
  #       displayName: 'Cleaning ArtifactStagingDirectory'
  #       steps:
  #         - template: azure-pipelines-templates/clean-artifact.yml