import {
  Apps24Regular,
  ArrowSort24Regular,
  ChevronDown24Filled,
  ChevronDown24Regular,
  ChevronLeft24Regular,
  ChevronRight24Regular,
  ChevronUp24Regular,
  Dismiss24Regular,
  DragRegular,
  Edit24Regular,
  EyeOff24Regular,
  Filter24Regular,
  FilterDismiss24Regular,
  Maximize24Regular,
  MoreHorizontal24Regular,
  Pin24Regular,
  PinOff24Regular,
  RowChild16Regular,
  Save24Regular,
  Search24Regular,
  Subtract24Regular,
  TableSimple24Regular,
  TextFont24Regular,
} from "@fluentui/react-icons";
import type { MRT_Icons } from "mantine-react-table";

export const IconsGridTableIMantineToFluent: Partial<MRT_Icons> = {
  IconArrowsSort: (props) => <ArrowSort24Regular {...props} />,
  IconBoxMultiple: (props) => <Apps24Regular {...props} />,
  IconChevronDown: (props) => <ChevronDown24Regular {...props} />,
  IconChevronLeft: (props) => <ChevronLeft24Regular {...props} />,
  IconChevronLeftPipe: (props) => <ChevronLeft24Regular {...props} />,
  IconChevronRight: (props) => <ChevronRight24Regular {...props} />,
  IconChevronRightPipe: (props) => <ChevronRight24Regular {...props} />,
  IconCircleX: (props) => <Dismiss24Regular {...props} />,
  IconClearAll: (props) => <Dismiss24Regular {...props} />,
  IconDeviceFloppy: (props) => <Save24Regular {...props} />,
  IconDots: (props) => <MoreHorizontal24Regular {...props} />,
  IconDotsVertical: (props) => <MoreHorizontal24Regular {...props} />,
  IconEdit: (props) => <Edit24Regular {...props} />,
  IconEyeOff: (props) => <EyeOff24Regular {...props} />,
  IconFilter: (props) => <Filter24Regular {...props} />,
  IconFilterCog: (props) => <Filter24Regular {...props} />,
  IconFilterOff: (props) => <FilterDismiss24Regular {...props} />,
  IconMaximize: (props) => <Maximize24Regular {...props} />,
  IconPinned: (props) => <Pin24Regular {...props} />,
  IconPinnedOff: (props) => <PinOff24Regular {...props} />,
  IconSearch: (props) => <Search24Regular {...props} />,
  IconSearchOff: (props) => <Dismiss24Regular {...props} />,
  IconSortAscending: (props) => <ChevronUp24Regular {...props} />,
  IconSortDescending: (props) => <ChevronDown24Regular {...props} />,
  IconX: (props) => <Dismiss24Regular {...props} />,
  IconMinimize: (props) => <Subtract24Regular {...props} />,
  IconColumns: (props) => <TableSimple24Regular {...props} />,
  IconBaselineDensityMedium: (props) => <TextFont24Regular {...props} />,
  IconBaselineDensitySmall: (props) => <TextFont24Regular {...props} />,
  IconChevronsDown: (props) => <ChevronDown24Filled {...props} />,
  IconArrowAutofitContent: (props) => <RowChild16Regular {...props} />,
  IconBaselineDensityLarge: (props) => <TextFont24Regular {...props} />,
  IconGripHorizontal: (props) => <DragRegular {...props} />,
};
