export const ChartYLabelMock = [
  {
    totalLinhas: 64,
    totalKmInicial: 0,
    totalKmFinal: 24,
    totalNrlinha: 10084,
    totalSeqsb: 36,
    childs: [
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-1",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1257,
        seqBd: 1,
        idSbl: "BSBL100000002P1",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-2",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1258,
        seqBd: 2,
        idSbl: "BSBL100000002P2",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-4",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1259,
        seqBd: 3,
        idSbl: "BSBL100000002P3",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-6",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1260,
        seqBd: 4,
        idSbl: "BSBL100000002P4",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-8",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1261,
        seqBd: 5,
        idSbl: "BSBL100000002P5",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-10",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1262,
        seqBd: 6,
        idSbl: "BSBL100000002P6",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-12",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1263,
        seqBd: 7,
        idSbl: "BSBL100000002P7",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
      {
        nomeApelido: "ISN",
        nomeSbl: "ISN-14",
        numeroKmInicial: 0,
        numeroKMFim: 3,
        numeroLinha: 1264,
        seqBd: 8,
        idSbl: "BSBL100000002P8",
        cdSgmt: "ISN",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 26,
        proporcaoCpKm: 0.3125,
        tipoVisao: "LD",
        linhas: 8,
      },
    ],
    nomeApelido: "ISN",
    nomeSbl: "ISN-1",
    numeroKmInicial: 0,
    numeroKMFim: 3,
    numeroLinha: 1257,
    seqBd: 1,
    idSbl: "BSBL100000002P1",
    cdSgmt: "ISN",
    cpKm: 2.5,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 26,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 8,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 6,
    totalKmFinal: 8,
    totalNrlinha: 2511,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IQA-ISN",
        nomeSbl: "IQA-ISN-1",
        numeroKmInicial: 3,
        numeroKMFim: 4,
        numeroLinha: 1255,
        seqBd: 1,
        idSbl: "BSBL100000002Oz",
        cdSgmt: "IQA-ISN",
        cpKm: 1.457,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 25,
        proporcaoCpKm: 0.7285,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IQA-ISN",
        nomeSbl: "IQA-ISN-2",
        numeroKmInicial: 3,
        numeroKMFim: 4,
        numeroLinha: 1256,
        seqBd: 2,
        idSbl: "BSBL100000002P0",
        cdSgmt: "IQA-ISN",
        cpKm: 1.457,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 25,
        proporcaoCpKm: 0.7285,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IQA-ISN",
    nomeSbl: "IQA-ISN-1",
    numeroKmInicial: 3,
    numeroKMFim: 4,
    numeroLinha: 1255,
    seqBd: 1,
    idSbl: "BSBL100000002Oz",
    cdSgmt: "IQA-ISN",
    cpKm: 1.457,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 25,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 8,
    totalKmFinal: 8,
    totalNrlinha: 2507,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IQA",
        nomeSbl: "IQA-1",
        numeroKmInicial: 4,
        numeroKMFim: 4,
        numeroLinha: 1253,
        seqBd: 1,
        idSbl: "BSBL100000002Ox",
        cdSgmt: "IQA",
        cpKm: 0.163,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 24,
        proporcaoCpKm: 0.0815,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IQA",
        nomeSbl: "IQA-2",
        numeroKmInicial: 4,
        numeroKMFim: 4,
        numeroLinha: 1254,
        seqBd: 2,
        idSbl: "BSBL100000002Oy",
        cdSgmt: "IQA",
        cpKm: 0.163,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 24,
        proporcaoCpKm: 0.0815,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IQA",
    nomeSbl: "IQA-1",
    numeroKmInicial: 4,
    numeroKMFim: 4,
    numeroLinha: 1253,
    seqBd: 1,
    idSbl: "BSBL100000002Ox",
    cdSgmt: "IQA",
    cpKm: 0.163,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 24,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 8,
    totalKmFinal: 16,
    totalNrlinha: 2503,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ICB-KK8-IQA",
        nomeSbl: "ICB-KM8-IQA-1",
        numeroKmInicial: 4,
        numeroKMFim: 8,
        numeroLinha: 1251,
        seqBd: 1,
        idSbl: "BSBL100000002Ov",
        cdSgmt: "ICB-KM8-IQA",
        cpKm: 3.845,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 23,
        proporcaoCpKm: 1.9225,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ICB-KK8-IQA",
        nomeSbl: "ICB-KM8-IQA-2",
        numeroKmInicial: 4,
        numeroKMFim: 8,
        numeroLinha: 1252,
        seqBd: 2,
        idSbl: "BSBL100000002Ow",
        cdSgmt: "ICB-KM8-IQA",
        cpKm: 3.845,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 23,
        proporcaoCpKm: 1.9225,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ICB-KK8-IQA",
    nomeSbl: "ICB-KM8-IQA-1",
    numeroKmInicial: 4,
    numeroKMFim: 8,
    numeroLinha: 1251,
    seqBd: 1,
    idSbl: "BSBL100000002Ov",
    cdSgmt: "ICB-KM8-IQA",
    cpKm: 3.845,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 23,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 16,
    totalKmFinal: 20,
    totalNrlinha: 2499,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ICB-KM8",
        nomeSbl: "ICB-KM8-1",
        numeroKmInicial: 8,
        numeroKMFim: 10,
        numeroLinha: 1249,
        seqBd: 1,
        idSbl: "BSBL100000002Ot",
        cdSgmt: "ICB-KM8",
        cpKm: 1.97,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 22,
        proporcaoCpKm: 0.985,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ICB-KM8",
        nomeSbl: "ICB-KM8-2",
        numeroKmInicial: 8,
        numeroKMFim: 10,
        numeroLinha: 1250,
        seqBd: 2,
        idSbl: "BSBL100000002Ou",
        cdSgmt: "ICB-KM8",
        cpKm: 1.97,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 22,
        proporcaoCpKm: 0.985,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ICB-KM8",
    nomeSbl: "ICB-KM8-1",
    numeroKmInicial: 8,
    numeroKMFim: 10,
    numeroLinha: 1249,
    seqBd: 1,
    idSbl: "BSBL100000002Ot",
    cdSgmt: "ICB-KM8",
    cpKm: 1.97,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 22,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 20,
    totalKmFinal: 24,
    totalNrlinha: 2495,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ICB-KM10",
        nomeSbl: "ICB-KM10-1",
        numeroKmInicial: 10,
        numeroKMFim: 12,
        numeroLinha: 1247,
        seqBd: 1,
        idSbl: "BSBL100000002Or",
        cdSgmt: "ICB-KM10",
        cpKm: 2.122,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 21,
        proporcaoCpKm: 1.061,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ICB-KM10",
        nomeSbl: "ICB-KM10-2",
        numeroKmInicial: 10,
        numeroKMFim: 12,
        numeroLinha: 1248,
        seqBd: 2,
        idSbl: "BSBL100000002Os",
        cdSgmt: "ICB-KM10",
        cpKm: 2.122,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 21,
        proporcaoCpKm: 1.061,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ICB-KM10",
    nomeSbl: "ICB-KM10-1",
    numeroKmInicial: 10,
    numeroKMFim: 12,
    numeroLinha: 1247,
    seqBd: 1,
    idSbl: "BSBL100000002Or",
    cdSgmt: "ICB-KM10",
    cpKm: 2.122,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 21,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 24,
    totalKmFinal: 26,
    totalNrlinha: 2491,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ICB",
        nomeSbl: "ICB-1",
        numeroKmInicial: 12,
        numeroKMFim: 13,
        numeroLinha: 1245,
        seqBd: 1,
        idSbl: "BSBL100000002Op",
        cdSgmt: "ICB",
        cpKm: 0.186,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 20,
        proporcaoCpKm: 0.093,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ICB",
        nomeSbl: "ICB-2",
        numeroKmInicial: 12,
        numeroKMFim: 13,
        numeroLinha: 1246,
        seqBd: 2,
        idSbl: "BSBL100000002Oq",
        cdSgmt: "ICB",
        cpKm: 0.186,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 20,
        proporcaoCpKm: 0.093,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ICB",
    nomeSbl: "ICB-1",
    numeroKmInicial: 12,
    numeroKMFim: 13,
    numeroLinha: 1245,
    seqBd: 1,
    idSbl: "BSBL100000002Op",
    cdSgmt: "ICB",
    cpKm: 0.186,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 20,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 26,
    totalKmFinal: 28,
    totalNrlinha: 2487,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ZPG-ICB",
        nomeSbl: "ZPG-ICB-1",
        numeroKmInicial: 13,
        numeroKMFim: 14,
        numeroLinha: 1243,
        seqBd: 1,
        idSbl: "BSBL100000002On",
        cdSgmt: "ZPG-ICB",
        cpKm: 1.508,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 19,
        proporcaoCpKm: 0.754,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ZPG-ICB",
        nomeSbl: "ZPG-ICB-2",
        numeroKmInicial: 13,
        numeroKMFim: 14,
        numeroLinha: 1244,
        seqBd: 2,
        idSbl: "BSBL100000002Oo",
        cdSgmt: "ZPG-ICB",
        cpKm: 1.508,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 19,
        proporcaoCpKm: 0.754,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ZPG-ICB",
    nomeSbl: "ZPG-ICB-1",
    numeroKmInicial: 13,
    numeroKMFim: 14,
    numeroLinha: 1243,
    seqBd: 1,
    idSbl: "BSBL100000002On",
    cdSgmt: "ZPG-ICB",
    cpKm: 1.508,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 19,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 28,
    totalKmFinal: 34,
    totalNrlinha: 2483,
    totalSeqsb: 1,
    childs: [
      {
        nomeApelido: "ZPG",
        nomeSbl: "ZPG-2",
        numeroKmInicial: 14,
        numeroKMFim: 17,
        numeroLinha: 1242,
        seqBd: 0,
        idSbl: "BSBL100000002Om",
        cdSgmt: "ZPG",
        cpKm: 2.549,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 18,
        proporcaoCpKm: 1.2745,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "ZPG",
        nomeSbl: "ZPG-1",
        numeroKmInicial: 14,
        numeroKMFim: 17,
        numeroLinha: 1241,
        seqBd: 1,
        idSbl: "BSBL100000002Ol",
        cdSgmt: "ZPG",
        cpKm: 2.549,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 18,
        proporcaoCpKm: 1.2745,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "ZPG",
    nomeSbl: "ZPG-2",
    numeroKmInicial: 14,
    numeroKMFim: 17,
    numeroLinha: 1242,
    seqBd: 0,
    idSbl: "BSBL100000002Om",
    cdSgmt: "ZPG",
    cpKm: 2.549,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 18,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 26,
    totalKmFinal: 28,
    totalNrlinha: 2479,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IAA-ZPG",
        nomeSbl: "IAA-ZPG-1",
        numeroKmInicial: 13,
        numeroKMFim: 14,
        numeroLinha: 1239,
        seqBd: 1,
        idSbl: "BSBL100000002Oj",
        cdSgmt: "IAA-ZPG",
        cpKm: 0.286,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 17,
        proporcaoCpKm: 0.143,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IAA-ZPG",
        nomeSbl: "IAA-ZPG-2",
        numeroKmInicial: 13,
        numeroKMFim: 14,
        numeroLinha: 1240,
        seqBd: 2,
        idSbl: "BSBL100000002Ok",
        cdSgmt: "IAA-ZPG",
        cpKm: 0.635,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 17,
        proporcaoCpKm: 0.143,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IAA-ZPG",
    nomeSbl: "IAA-ZPG-1",
    numeroKmInicial: 13,
    numeroKMFim: 14,
    numeroLinha: 1239,
    seqBd: 1,
    idSbl: "BSBL100000002Oj",
    cdSgmt: "IAA-ZPG",
    cpKm: 0.286,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 17,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 25,
    totalKmInicial: 70,
    totalKmFinal: 80,
    totalNrlinha: 6180,
    totalSeqsb: 19,
    childs: [
      {
        nomeApelido: "IAA",
        nomeSbl: "IAA-1",
        numeroKmInicial: 14,
        numeroKMFim: 16,
        numeroLinha: 1234,
        seqBd: 1,
        idSbl: "BSBL100000002Oe",
        cdSgmt: "IAA",
        cpKm: 1.769,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 16,
        proporcaoCpKm: 0.3538,
        tipoVisao: "LD",
        linhas: 5,
      },
      {
        nomeApelido: "IAA",
        nomeSbl: "IAA-3",
        numeroKmInicial: 14,
        numeroKMFim: 16,
        numeroLinha: 1235,
        seqBd: 3,
        idSbl: "BSBL100000002Of",
        cdSgmt: "IAA",
        cpKm: 1.769,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 16,
        proporcaoCpKm: 0.3538,
        tipoVisao: "LD",
        linhas: 5,
      },
      {
        nomeApelido: "IAA",
        nomeSbl: "IAA-5",
        numeroKmInicial: 14,
        numeroKMFim: 16,
        numeroLinha: 1236,
        seqBd: 4,
        idSbl: "BSBL100000002Og",
        cdSgmt: "IAA",
        cpKm: 1.701,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 16,
        proporcaoCpKm: 0.3538,
        tipoVisao: "LD",
        linhas: 5,
      },
      {
        nomeApelido: "IAA",
        nomeSbl: "IAA-7",
        numeroKmInicial: 14,
        numeroKMFim: 16,
        numeroLinha: 1237,
        seqBd: 5,
        idSbl: "BSBL100000002Oh",
        cdSgmt: "IAA",
        cpKm: 1.64,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 16,
        proporcaoCpKm: 0.3538,
        tipoVisao: "LD",
        linhas: 5,
      },
      {
        nomeApelido: "IAA",
        nomeSbl: "IAA-9",
        numeroKmInicial: 14,
        numeroKMFim: 16,
        numeroLinha: 1238,
        seqBd: 6,
        idSbl: "BSBL100000002Oi",
        cdSgmt: "IAA",
        cpKm: 1.55,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 16,
        proporcaoCpKm: 0.3538,
        tipoVisao: "LD",
        linhas: 5,
      },
    ],
    nomeApelido: "IAA",
    nomeSbl: "IAA-1",
    numeroKmInicial: 14,
    numeroKMFim: 16,
    numeroLinha: 1234,
    seqBd: 1,
    idSbl: "BSBL100000002Oe",
    cdSgmt: "IAA",
    cpKm: 1.769,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 16,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 5,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 32,
    totalKmFinal: 32,
    totalNrlinha: 2465,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IAA-IFA",
        nomeSbl: "IAA-IFA-1",
        numeroKmInicial: 16,
        numeroKMFim: 16,
        numeroLinha: 1232,
        seqBd: 1,
        idSbl: "BSBL100000002Oc",
        cdSgmt: "IAA-IFA",
        cpKm: 0.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 15,
        proporcaoCpKm: 0.25,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IAA-IFA",
        nomeSbl: "IAA-IFA-2",
        numeroKmInicial: 16,
        numeroKMFim: 16,
        numeroLinha: 1233,
        seqBd: 2,
        idSbl: "BSBL100000002Od",
        cdSgmt: "IAA-IFA",
        cpKm: 0.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 15,
        proporcaoCpKm: 0.25,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IAA-IFA",
    nomeSbl: "IAA-IFA-1",
    numeroKmInicial: 16,
    numeroKMFim: 16,
    numeroLinha: 1232,
    seqBd: 1,
    idSbl: "BSBL100000002Oc",
    cdSgmt: "IAA-IFA",
    cpKm: 0.5,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 15,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 1,
    totalKmInicial: 16,
    totalKmFinal: 16,
    totalNrlinha: 1231,
    totalSeqsb: 1,
    childs: [
      {
        nomeApelido: "IAA-IFA-2",
        nomeSbl: "IAA-IFA-2-1",
        numeroKmInicial: 16,
        numeroKMFim: 16,
        numeroLinha: 1231,
        seqBd: 1,
        idSbl: "BSBL100000002Ob",
        cdSgmt: "IAA-IFA-2",
        cpKm: 0.156,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 14,
        proporcaoCpKm: 0.156,
        tipoVisao: null,
        linhas: 1,
      },
    ],
    nomeApelido: "IAA-IFA-2",
    nomeSbl: "IAA-IFA-2-1",
    numeroKmInicial: 16,
    numeroKMFim: 16,
    numeroLinha: 1231,
    seqBd: 1,
    idSbl: "BSBL100000002Ob",
    cdSgmt: "IAA-IFA-2",
    cpKm: 0.156,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 14,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 1,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 0,
    totalKmFinal: 2,
    totalNrlinha: 2459,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IFA",
        nomeSbl: "IFA-1",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1229,
        seqBd: 1,
        idSbl: "BSBL100000002O[",
        cdSgmt: "IFA",
        cpKm: 1.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 13,
        proporcaoCpKm: 0.75,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IFA",
        nomeSbl: "IFA-2",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1230,
        seqBd: 2,
        idSbl: "BSBL100000002Oa",
        cdSgmt: "IFA",
        cpKm: 1.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 13,
        proporcaoCpKm: 0.75,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IFA",
    nomeSbl: "IFA-1",
    numeroKmInicial: 0,
    numeroKMFim: 1,
    numeroLinha: 1229,
    seqBd: 1,
    idSbl: "BSBL100000002O[",
    cdSgmt: "IFA",
    cpKm: 1.5,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 13,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 9,
    totalKmInicial: 48,
    totalKmFinal: 54,
    totalNrlinha: 3681,
    totalSeqsb: 6,
    childs: [
      {
        nomeApelido: "IPG-IAA",
        nomeSbl: "IPG-IAA-1",
        numeroKmInicial: 16,
        numeroKMFim: 18,
        numeroLinha: 1226,
        seqBd: 1,
        idSbl: "BSBL100000002OX",
        cdSgmt: "IPG-IAA",
        cpKm: 1.782,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 12,
        proporcaoCpKm: 0.594,
        tipoVisao: "LD",
        linhas: 3,
      },
      {
        nomeApelido: "IPG-IAA",
        nomeSbl: "IPG-IAA-2",
        numeroKmInicial: 16,
        numeroKMFim: 18,
        numeroLinha: 1227,
        seqBd: 2,
        idSbl: "BSBL100000002OY",
        cdSgmt: "IPG-IAA",
        cpKm: 1.782,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 12,
        proporcaoCpKm: 0.594,
        tipoVisao: "LD",
        linhas: 3,
      },
      {
        nomeApelido: "IPG-IAA",
        nomeSbl: "IPG-IAA-4",
        numeroKmInicial: 16,
        numeroKMFim: 18,
        numeroLinha: 1228,
        seqBd: 3,
        idSbl: "BSBL100000002OZ",
        cdSgmt: "IPG-IAA",
        cpKm: 1.782,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 12,
        proporcaoCpKm: 0.594,
        tipoVisao: "LD",
        linhas: 3,
      },
    ],
    nomeApelido: "IPG-IAA",
    nomeSbl: "IPG-IAA-1",
    numeroKmInicial: 16,
    numeroKMFim: 18,
    numeroLinha: 1226,
    seqBd: 1,
    idSbl: "BSBL100000002OX",
    cdSgmt: "IPG-IAA",
    cpKm: 1.782,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 12,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 3,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 36,
    totalKmFinal: 36,
    totalNrlinha: 4299,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IPG-E",
        nomeSbl: "IPG-E-1",
        numeroKmInicial: 18,
        numeroKMFim: 18,
        numeroLinha: 2149,
        seqBd: 1,
        idSbl: "BSBL100000002bx",
        cdSgmt: "IPG-E",
        cpKm: 0.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 11,
        proporcaoCpKm: 0.25,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IPG-E",
        nomeSbl: "IPG-E-2",
        numeroKmInicial: 18,
        numeroKMFim: 18,
        numeroLinha: 2150,
        seqBd: 2,
        idSbl: "BSBL100000002by",
        cdSgmt: "IPG-E",
        cpKm: 0.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 11,
        proporcaoCpKm: 0.25,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IPG-E",
    nomeSbl: "IPG-E-1",
    numeroKmInicial: 18,
    numeroKMFim: 18,
    numeroLinha: 2149,
    seqBd: 1,
    idSbl: "BSBL100000002bx",
    cdSgmt: "IPG-E",
    cpKm: 0.5,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 11,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 36,
    totalKmFinal: 38,
    totalNrlinha: 2445,
    totalSeqsb: 6,
    childs: [
      {
        nomeApelido: "IPG-2",
        nomeSbl: "IPG-2-6",
        numeroKmInicial: 18,
        numeroKMFim: 19,
        numeroLinha: 1222,
        seqBd: 1,
        idSbl: "BSBL100000002OT",
        cdSgmt: "IPG-2",
        cpKm: 0.752,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 10,
        proporcaoCpKm: 0.376,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IPG-2",
        nomeSbl: "IPG-2-16",
        numeroKmInicial: 18,
        numeroKMFim: 19,
        numeroLinha: 1223,
        seqBd: 5,
        idSbl: "BSBL100000002OU",
        cdSgmt: "IPG-2",
        cpKm: 0.744,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 10,
        proporcaoCpKm: 0.376,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IPG-2",
    nomeSbl: "IPG-2-6",
    numeroKmInicial: 18,
    numeroKMFim: 19,
    numeroLinha: 1222,
    seqBd: 1,
    idSbl: "BSBL100000002OT",
    cdSgmt: "IPG-2",
    cpKm: 0.752,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 10,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 36,
    totalKmFinal: 40,
    totalNrlinha: 4301,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IPG-W",
        nomeSbl: "IPG-W-1",
        numeroKmInicial: 18,
        numeroKMFim: 20,
        numeroLinha: 2148,
        seqBd: 1,
        idSbl: "BSBL100000002bw",
        cdSgmt: "IPG-W",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 9,
        proporcaoCpKm: 1.25,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IPG-W",
        nomeSbl: "IPG-W-2",
        numeroKmInicial: 18,
        numeroKMFim: 20,
        numeroLinha: 2153,
        seqBd: 2,
        idSbl: "BSBL100000002c3",
        cdSgmt: "IPG-W",
        cpKm: 2.5,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 9,
        proporcaoCpKm: 1.25,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IPG-W",
    nomeSbl: "IPG-W-1",
    numeroKmInicial: 18,
    numeroKMFim: 20,
    numeroLinha: 2148,
    seqBd: 1,
    idSbl: "BSBL100000002bw",
    cdSgmt: "IPG-W",
    cpKm: 2.5,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 9,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 9,
    totalKmInicial: 54,
    totalKmFinal: 60,
    totalNrlinha: 4596,
    totalSeqsb: 6,
    childs: [
      {
        nomeApelido: "IPG",
        nomeSbl: "IPG-1",
        numeroKmInicial: 18,
        numeroKMFim: 20,
        numeroLinha: 1224,
        seqBd: 1,
        idSbl: "BSBL100000002OV",
        cdSgmt: "IPG",
        cpKm: 1.662,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 8,
        proporcaoCpKm: 0.554,
        tipoVisao: "LD",
        linhas: 3,
      },
      {
        nomeApelido: "IPG",
        nomeSbl: "IPG-2",
        numeroKmInicial: 18,
        numeroKMFim: 20,
        numeroLinha: 1225,
        seqBd: 2,
        idSbl: "BSBL100000002OW",
        cdSgmt: "IPG",
        cpKm: 1.662,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 8,
        proporcaoCpKm: 0.554,
        tipoVisao: "LD",
        linhas: 3,
      },
      {
        nomeApelido: "IPG",
        nomeSbl: "IPG-3",
        numeroKmInicial: 18,
        numeroKMFim: 20,
        numeroLinha: 2147,
        seqBd: 3,
        idSbl: "BSBL100000002bv",
        cdSgmt: "IPG",
        cpKm: 1.662,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 8,
        proporcaoCpKm: 0.554,
        tipoVisao: "LD",
        linhas: 3,
      },
    ],
    nomeApelido: "IPG",
    nomeSbl: "IPG-1",
    numeroKmInicial: 18,
    numeroKMFim: 20,
    numeroLinha: 1224,
    seqBd: 1,
    idSbl: "BSBL100000002OV",
    cdSgmt: "IPG",
    cpKm: 1.662,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 8,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 3,
  },
  {
    totalLinhas: 1,
    totalKmInicial: 0,
    totalKmFinal: 0,
    totalNrlinha: 1216,
    totalSeqsb: 1,
    childs: [
      {
        nomeApelido: "IUF-IPG",
        nomeSbl: "IUF-IPG-1",
        numeroKmInicial: 0,
        numeroKMFim: 0,
        numeroLinha: 1216,
        seqBd: 1,
        idSbl: "BSBL100000002ON",
        cdSgmt: "IUF-IPG",
        cpKm: 0.113,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 7,
        proporcaoCpKm: 0.113,
        tipoVisao: "LD",
        linhas: 1,
      },
    ],
    nomeApelido: "IUF-IPG",
    nomeSbl: "IUF-IPG-1",
    numeroKmInicial: 0,
    numeroKMFim: 0,
    numeroLinha: 1216,
    seqBd: 1,
    idSbl: "BSBL100000002ON",
    cdSgmt: "IUF-IPG",
    cpKm: 0.113,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 7,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 1,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 0,
    totalKmFinal: 0,
    totalNrlinha: 4325,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "IUF-E",
        nomeSbl: "IUF-E-1",
        numeroKmInicial: 0,
        numeroKMFim: 0,
        numeroLinha: 2162,
        seqBd: 1,
        idSbl: "BSBL100000002cJ",
        cdSgmt: "IUF-E",
        cpKm: 0.1,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 6,
        proporcaoCpKm: 0.05,
        tipoVisao: "LD",
        linhas: 2,
      },
      {
        nomeApelido: "IUF-E",
        nomeSbl: "IUF-E-2",
        numeroKmInicial: 0,
        numeroKMFim: 0,
        numeroLinha: 2163,
        seqBd: 2,
        idSbl: "BSBL100000002cK",
        cdSgmt: "IUF-E",
        cpKm: 0.87,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 6,
        proporcaoCpKm: 0.05,
        tipoVisao: "LD",
        linhas: 2,
      },
    ],
    nomeApelido: "IUF-E",
    nomeSbl: "IUF-E-1",
    numeroKmInicial: 0,
    numeroKMFim: 0,
    numeroLinha: 2162,
    seqBd: 1,
    idSbl: "BSBL100000002cJ",
    cdSgmt: "IUF-E",
    cpKm: 0.1,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 6,
    proporcaoCpKm: 0,
    tipoVisao: "LD",
    linhas: 2,
  },
  {
    totalLinhas: 16,
    totalKmInicial: 0,
    totalKmFinal: 4,
    totalNrlinha: 4854,
    totalSeqsb: 10,
    childs: [
      {
        nomeApelido: "IUF",
        nomeSbl: "IUF-1",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1212,
        seqBd: 1,
        idSbl: "BSBL100000002OJ",
        cdSgmt: "IUF",
        cpKm: 1.365,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 5,
        proporcaoCpKm: 0.34125,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IUF",
        nomeSbl: "IUF-2",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1213,
        seqBd: 2,
        idSbl: "BSBL100000002OK",
        cdSgmt: "IUF",
        cpKm: 0.595,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 5,
        proporcaoCpKm: 0.34125,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IUF",
        nomeSbl: "IUF-VLI-1",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1214,
        seqBd: 3,
        idSbl: "BSBL100000002OL",
        cdSgmt: "IUF",
        cpKm: 1.505,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 5,
        proporcaoCpKm: 0.34125,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IUF",
        nomeSbl: "IUF-VLI-3",
        numeroKmInicial: 0,
        numeroKMFim: 1,
        numeroLinha: 1215,
        seqBd: 4,
        idSbl: "BSBL100000002OM",
        cdSgmt: "IUF",
        cpKm: 1.505,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 5,
        proporcaoCpKm: 0.34125,
        tipoVisao: null,
        linhas: 4,
      },
    ],
    nomeApelido: "IUF",
    nomeSbl: "IUF-1",
    numeroKmInicial: 0,
    numeroKMFim: 1,
    numeroLinha: 1212,
    seqBd: 1,
    idSbl: "BSBL100000002OJ",
    cdSgmt: "IUF",
    cpKm: 1.365,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 5,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 4,
  },
  {
    totalLinhas: 1,
    totalKmInicial: 1,
    totalKmFinal: 7,
    totalNrlinha: 1211,
    totalSeqsb: 1,
    childs: [
      {
        nomeApelido: "IBA-IUF",
        nomeSbl: "IBA-IUF-1",
        numeroKmInicial: 1,
        numeroKMFim: 7,
        numeroLinha: 1211,
        seqBd: 1,
        idSbl: "BSBL100000002OI",
        cdSgmt: "IBA-IUF",
        cpKm: 6.115,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 4,
        proporcaoCpKm: 6.115,
        tipoVisao: null,
        linhas: 1,
      },
    ],
    nomeApelido: "IBA-IUF",
    nomeSbl: "IBA-IUF-1",
    numeroKmInicial: 1,
    numeroKMFim: 7,
    numeroLinha: 1211,
    seqBd: 1,
    idSbl: "BSBL100000002OI",
    cdSgmt: "IBA-IUF",
    cpKm: 6.115,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 4,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 1,
  },
  {
    totalLinhas: 16,
    totalKmInicial: 28,
    totalKmFinal: 36,
    totalNrlinha: 4834,
    totalSeqsb: 10,
    childs: [
      {
        nomeApelido: "IBA",
        nomeSbl: "IBA-1",
        numeroKmInicial: 7,
        numeroKMFim: 9,
        numeroLinha: 1207,
        seqBd: 1,
        idSbl: "BSBL100000002OE",
        cdSgmt: "IBA",
        cpKm: 1.66,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 3,
        proporcaoCpKm: 0.415,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IBA",
        nomeSbl: "IBA-3",
        numeroKmInicial: 7,
        numeroKMFim: 9,
        numeroLinha: 1208,
        seqBd: 2,
        idSbl: "BSBL100000002OF",
        cdSgmt: "IBA",
        cpKm: 1.556,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 3,
        proporcaoCpKm: 0.415,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IBA",
        nomeSbl: "IBA-SUZ-1",
        numeroKmInicial: 7,
        numeroKMFim: 9,
        numeroLinha: 1209,
        seqBd: 3,
        idSbl: "BSBL100000002OG",
        cdSgmt: "IBA",
        cpKm: 1.556,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 3,
        proporcaoCpKm: 0.415,
        tipoVisao: null,
        linhas: 4,
      },
      {
        nomeApelido: "IBA",
        nomeSbl: "IBA-DWO-1",
        numeroKmInicial: 7,
        numeroKMFim: 9,
        numeroLinha: 1210,
        seqBd: 4,
        idSbl: "BSBL100000002OH",
        cdSgmt: "IBA",
        cpKm: 1.556,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 3,
        proporcaoCpKm: 0.415,
        tipoVisao: null,
        linhas: 4,
      },
    ],
    nomeApelido: "IBA",
    nomeSbl: "IBA-1",
    numeroKmInicial: 7,
    numeroKMFim: 9,
    numeroLinha: 1207,
    seqBd: 1,
    idSbl: "BSBL100000002OE",
    cdSgmt: "IBA",
    cpKm: 1.66,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 3,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 4,
  },
  {
    totalLinhas: 1,
    totalKmInicial: 9,
    totalKmFinal: 14,
    totalNrlinha: 1206,
    totalSeqsb: 1,
    childs: [
      {
        nomeApelido: "ICZ-IBA",
        nomeSbl: "ICZ-IBA-1",
        numeroKmInicial: 9,
        numeroKMFim: 14,
        numeroLinha: 1206,
        seqBd: 1,
        idSbl: "BSBL100000002OD",
        cdSgmt: "ICZ-IBA",
        cpKm: 5.239,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 2,
        proporcaoCpKm: 5.239,
        tipoVisao: null,
        linhas: 1,
      },
    ],
    nomeApelido: "ICZ-IBA",
    nomeSbl: "ICZ-IBA-1",
    numeroKmInicial: 9,
    numeroKMFim: 14,
    numeroLinha: 1206,
    seqBd: 1,
    idSbl: "BSBL100000002OD",
    cdSgmt: "ICZ-IBA",
    cpKm: 5.239,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 2,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 1,
  },
  {
    totalLinhas: 4,
    totalKmInicial: 28,
    totalKmFinal: 34,
    totalNrlinha: 2409,
    totalSeqsb: 3,
    childs: [
      {
        nomeApelido: "ICZ",
        nomeSbl: "ICZ-1",
        numeroKmInicial: 14,
        numeroKMFim: 17,
        numeroLinha: 1204,
        seqBd: 1,
        idSbl: "BSBL100000002OB",
        cdSgmt: "ICZ",
        cpKm: 2.408,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 1,
        proporcaoCpKm: 1.204,
        tipoVisao: null,
        linhas: 2,
      },
      {
        nomeApelido: "ICZ",
        nomeSbl: "ICZ-2",
        numeroKmInicial: 14,
        numeroKMFim: 17,
        numeroLinha: 1205,
        seqBd: 2,
        idSbl: "BSBL100000002OC",
        cdSgmt: "ICZ",
        cpKm: 2.408,
        dcSgmt: 0,
        nmRamal: 0,
        nuRamal: "10062",
        icPljmExcsRamal: "T",
        seqSegment: 1,
        proporcaoCpKm: 1.204,
        tipoVisao: null,
        linhas: 2,
      },
    ],
    nomeApelido: "ICZ",
    nomeSbl: "ICZ-1",
    numeroKmInicial: 14,
    numeroKMFim: 17,
    numeroLinha: 1204,
    seqBd: 1,
    idSbl: "BSBL100000002OB",
    cdSgmt: "ICZ",
    cpKm: 2.408,
    dcSgmt: 0,
    nmRamal: 0,
    nuRamal: "10062",
    icPljmExcsRamal: "T",
    seqSegment: 1,
    proporcaoCpKm: 0,
    tipoVisao: null,
    linhas: 2,
  },
];

export const ChartTrainsMock = [
  {
    dataOficializacao: "2025-06-30T16:16:45",
    cor: "128,0,0,",
    tipoTrem: "CARGA GERAL",
    comprimentoKm: 1.3,
    id: "BTREM0000000A4y",
    idExterno: "0000gF000000B5a1",
    prefixo: "IIN2160",
    prefixoOutraFerrovia: "V32",
    dataProntidao: "2025-06-30T05:15:00Z",
    estado: 1,
    origem: "ZPG",
    destino: "ISN",
    patioExterno: "ZPG",
    previsaoPartida: "2025-06-30T05:15:00Z",
    previsaoSaida: "2025-06-30T16:36:57Z",
    tabela: "",
    dataBaseCarregamento: "2025-06-30T16:12:32Z",
    zonaOficial: "MESA4",
    movimentos: [
      {
        id: "104",
        segmento: "ZPG",
        alias: "ZPG",
        linha: "ZPG-1", // yi
        destino: "ZPG-ICB-1", // yf
        chegada: "2025-06-30T16:22:32Z", // xi
        fimCurso: "2025-06-30T16:32:05Z",
        partida: "2025-06-30T16:32:05Z", // xf
        fimOcupacao: "2025-06-30T16:36:57Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "204",
        segmento: "ZPG-ICB",
        alias: "ZPG-ICB",
        linha: "ZPG-ICB-1",
        destino: "ICB-KM10-1", // yf
        chegada: "2025-06-30T16:32:05Z",
        fimCurso: "2025-06-30T16:37:44Z",
        partida: "2025-06-30T16:37:44Z",
        fimOcupacao: "2025-06-30T16:42:53Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "304",
        segmento: "ICB",
        alias: "ICB",
        linha: "ICB-KM10-1",
        destino: "ICB-KM10-1", // yf
        chegada: "2025-06-30T16:37:44Z",
        fimCurso: "2025-06-30T16:38:25Z",
        partida: "2025-06-30T16:38:25Z",
        fimOcupacao: "2025-06-30T16:43:37Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "404",
        segmento: "ICB-KM10",
        alias: "ICB-KM10",
        linha: "ICB-KM10-1",
        destino: "ICB-KM8-1", // yf
        chegada: "2025-06-30T16:38:25Z",
        fimCurso: "2025-06-30T16:45:45Z",
        partida: "2025-06-30T16:45:45Z",
        fimOcupacao: "2025-06-30T16:50:57Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "504",
        segmento: "ICB-KM8",
        alias: "ICB-KM8",
        linha: "ICB-KM8-1",
        destino: "ICB-KM8-IQA-1", // yf
        chegada: "2025-06-30T16:45:45Z",
        fimCurso: "2025-06-30T16:52:41Z",
        partida: "2025-06-30T16:52:41Z",
        fimOcupacao: "2025-06-30T16:57:53Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "604",
        segmento: "ICB-KM8-IQA",
        alias: "ICB-KK8-IQA",
        linha: "ICB-KM8-IQA-1",
        destino: "IQA-1", // yf
        chegada: "2025-06-30T16:52:41Z",
        fimCurso: "2025-06-30T17:04:31Z",
        partida: "2025-06-30T17:04:31Z",
        fimOcupacao: "2025-06-30T17:09:23Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "704",
        segmento: "IQA",
        alias: "IQA",
        linha: "IQA-1",
        destino: "IQA-ISN-1", // yf
        chegada: "2025-06-30T17:04:31Z",
        fimCurso: "2025-06-30T17:05:07Z",
        partida: "2025-06-30T17:05:07Z",
        fimOcupacao: "2025-06-30T17:09:59Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "804",
        segmento: "IQA-ISN",
        alias: "IQA-ISN",
        linha: "IQA-ISN-1",
        destino: "ISN-1", // yf
        chegada: "2025-06-30T17:05:07Z",
        fimCurso: "2025-06-30T17:10:34Z",
        partida: "2025-06-30T17:10:34Z",
        fimOcupacao: "2025-06-30T17:15:46Z",
        idFicha: "BFICA0000000dj2",
      },
      {
        id: "904",
        segmento: "ISN",
        alias: "ISN",
        linha: "ISN-1",
        destino: "ISN-1", // yf
        chegada: "2025-06-30T17:10:34Z",
        fimCurso: "2025-06-30T17:18:09Z",
        partida: "2025-06-30T17:18:09Z",
        fimOcupacao: "2025-06-30T17:18:09Z",
        idFicha: "BFICA0000000dj2",
      },
    ],
  },
];
